spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.141:3306/activiti7?autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
  activiti:
    db-history-used: true # 使用历史表
    history-level: audit # 对历史表进行记录
